# Generated by Django 2.0.1 on 2018-03-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('coin_name', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('class_name', models.CharField(default='', max_length=50)),
                ('coinmarketcap', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=False, verbose_name='Active Currency')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TopCoins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('total_supply', models.BigIntegerField(default=0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('time', models.BigIntegerField(default=0, verbose_name='Date of Price')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Currency')),
            ],
            options={
                'ordering': ('currency',),
            },
        ),
        migrations.CreateModel(
            name='Xchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(default='0', max_length=200, unique=True)),
                ('api_url', models.CharField(default='0', max_length=200)),
                ('api_key', models.CharField(default='0', max_length=200)),
                ('api_secret', models.CharField(default='0', max_length=200)),
                ('start_date', models.BigIntegerField(default=0, verbose_name='start date')),
                ('end_date', models.BigIntegerField(default=0, verbose_name='end date')),
                ('number_symbols', models.IntegerField(default=0, verbose_name='number of symbols')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='topcoins',
            name='xchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeCoins.Xchange'),
        ),
    ]
